package org.example.model;

public enum SagaStatus {
    STARTED,
    USER_CREATED,
    NOTIFICATION_SENT,
    NOTIFICATION_FAILED,
    CABINET_CREATING,
    CABINET_CREATED,
    CABINET_FAILED,
    NUTRITION_CALCULATING,
    NUTRITION_CALCULATED,
    NUTRITION_FAILED,
    COMPLETED,
    COMPENSATING,
    COMPENSATED,
    FAILED
}
